### ISSUE TITLE
Server table view is missing

### ISSUE THREAD

**Issue by losuler** [iNPUTmice/caas#59]
I can't seem to find the really useful table view that listed all the servers any more.

**Comment by iNPUTmice** [comment]
We removed it because we figured that the vast majority of users are interested in the results for one particular server. The current interface makes that much more easy to access compared to Strg-F the full list.
As a source for recommendation this old table view wasn’t very useful either because its size was way too overwhelming. (Also just picking something green is a bad strategy for choosing a server.)

But out of curiosity: Why did you find the table 'really useful'. Maybe what ever you got out of the table can be reincorporated in a better form.

**Comment by losuler** [comment]
I suppose it felt to me as the easiest way to narrow down servers which I felt were run by someone who either had their server up to date or was keeping up with the latest developments to XMPP. I understand however that a reason why this might be a bad strategy for choosing a server could be because there might be other reasons for not enabling certain extensions.

I did notice it does say this in the [about section](https://compliance.conversations.im/about/) at the moment though,

> Using this web service you can choose a good quality server by comparing the servers which have implemented the latest specifications and which servers have been fast at implementing new specifications historically.

I understand if you think the scope of this site should be limited to providing compliance of individual servers and that what I'm suggesting should be realised in another site that incorporates information provided by this one, in-conjunction with other information similar to https://xmpp-servers.404.city, except this site still requires a user to look at the almost 80 different servers.
